name: Build artifacts
    
on:
  workflow_call:
    inputs:
      version:
        description: 'version tag'
        required: true
        type: string
      release:
        description: 'Type of Build'
        required: true
        type: string
      commit:
        description: 'commit hash'
        required: true
        type: string
      docker:
        description: "Build docker"
        required: true
        type: boolean
      flatpak:
        description: "Build flatpak"
        required: true
        type: boolean
      wine:
        description: "Build wine"
        required: true
        type: boolean
        
    outputs:
      flatpak_yaml_artifact_url:
        value: ${{ jobs.build-flatpak.outputs.artifact_url }}

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo version: ${{ inputs.version }}
          echo release: ${{ inputs.release }}
          echo commit: ${{ inputs.commit }}
          echo docker: ${{ inputs.docker }}
          echo flatpak: ${{ inputs.flatpak }}
          echo version: ${{ inputs.version }}
  build-wine:
    uses: ./.forgejo/workflows/wix.yaml
    if: ${{ inputs.wine }}
    with:
      version: ${{ inputs.version }}
      commit: ${{ inputs.commit }}

  build-docker:
    uses: ./.forgejo/workflows/docker.yaml
    if: ${{ inputs.docker }}
    with:
      version: ${{ inputs.version }}
      commit: ${{ inputs.commit }}
      push: "false"
      release: ${{ inputs.release }}

  build-flatpak:
    uses: ./.forgejo/workflows/flatpak.yaml
    if: ${{ inputs.flatpak }}
    with:
      version: ${{ inputs.version }}
      commit: ${{ inputs.commit }}
  
      
