name: Build artifacts
    
on:
  workflow_call:
    inputs:
      version:
        description: 'version tag'
        required: true
        type: string
      release:
        description: 'Type of Build'
        required: true
        type: string
      commit:
        description: 'commit hash'
        required: true
        type: string
      image_name:
        required: true
        type: string
        
    outputs:
      flatpak_yaml_artifact_url:
        value: ${{ jobs.build-flatpak.outputs.artifact_url }}

jobs:
  build-wine:
    uses: ./.forgejo/workflows/wix.yaml
    with:
      version: ${{ inputs.version }}
      commit: ${{ inputs.commit }}

  build-docker:
    uses: ./.forgejo/workflows/docker.yaml
    with:
      version: ${{ inputs.version }}
      commit: ${{ inputs.commit }}
      push: "false"
      release: ${{ inputs.release }}
      image_name: ${{ inputs.image_name }}

  build-flatpak:
    uses: ./.forgejo/workflows/flatpak.yaml
    with:
      version: ${{ inputs.version }}
      commit: ${{ inputs.commit }}
  
      
