name: Check

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

enable-email-notifications: true

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install and poetry and all dependencies
        run: |
          pip install uv --quiet
      - name: Run mypy
        run: uv run --extra client mypy syng --strict

  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install ruff
        run: pip install ruff --quiet
      - name: Run ruff
        run: ruff check syng 
