name: Just debug things

on:
  workflow_dispatch:
    inputs:
      release:
        description: "release"
        type: string
        required: true

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: print inputs
        run: |
          echo "type: ${{ inputs.release }}"

