name: build flatpak
on:
  workflow_dispatch: {}

jobs:
  prepare-yaml-files:
    runs-on: privileged-ubuntu-latest
    container: 
      image: git.k-fortytwo.de/christofsteel/flatpakkde:6.10-new
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Flatpak and flatpak-builder
        uses: https://github.com/awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: gettext-base python3-requirement-parser python3-yaml xvfb
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.11.19"      
      - name: Prepare Flatpak YAML files
        run: |
          chmod +x build_yaml.sh
          dbus-daemon --system
          xvfb-run -a -s "-screen 0 1024x768x24" -- \
          dbus-run-session \
          ./build_yaml.sh
        working-directory: resources/flatpak
      - uses: actions/upload-artifact@v3
        with:
          name: flatpak-yaml-files
          path: resources/flatpak
      
  build-flatpak:
    needs: prepare-yaml-files
    runs-on: privileged-ubuntu-latest
    container: 
      image: git.k-fortytwo.de/christofsteel/flatpakkde:6.10-new
    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: flatpak-yaml-files
          path: .

      # - run: |
      #     apt update
      #     apt-get install -y flatpak flatpak-builder
      - name: Install Flatpak and flatpak-builder
        uses: https://github.com/awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: xvfb

      # - name: Build Flatpak
      #   uses: https://codeberg.org/jamiemurphy/flatpak-runtime-sdk@main
      #   with:
      #     manifest-path: /workspace/christofsteel/syng-deploytest/rocks.syng.Syng.yaml
      #     module: Syng.Rocks!
      #     app-id: rocks.syng.Syng
      #     bundle: rocks.syng.Syng.flatpak


      # - name: Install Flatpak and flatpak-builder
      #   uses: https://github.com/awalsh128/cache-apt-pkgs-action@v1
      #   with:
      #     packages: gettext-base python3-requirement-parser python3-yaml
        #
      - run: ls -l


      - name: Build Flatpak
        run: |
          dbus-daemon --system
          xvfb-run -a -s "-screen 0 1024x768x24" -- \
          dbus-run-session \
          flatpak run --user --command=flathub-build org.flatpak.Builder --disable-rofiles-fuse --repo=repo rocks.syng.Syng.yaml
        # working-directory: /workspace/christofsteel/syng-deploytest
      - name: Build Flatpak Artifact
        run: flatpak build-bundle /workspace/christofsteel/syng-deploytest/repo "rocks.syng.Syng.flatpak" "rocks.syng.Syng"
        # working-directory: /workspace/christofsteel/syng-deploytest/

      - name: Upload Flatpak artifact
        uses: actions/upload-artifact@v3
        with:
          name: flatpak-bundle
          path: "*.flatpak"

      
