name: draft a release on github (testrepo)

on:
  workflow_dispatch: {}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -alh > /dev/stderr
      - uses: https://git.k-fortytwo.de/actions/gh-release@7c257daf15ec012b27e7c1a279060e599f82990a
        with:
          repo: christofsteel/testrepo
          tag: gh-testrelease
          auth-token: ${{ secrets.GH_TESTREPO_CONTENTS_WRITE }}
          commitish: main
          files: pyproject.toml
