name: draft a release on github (testrepo)

on:
  workflow_dispatch: {}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -alh > /dev/stderr
      - uses: https://git.k-fortytwo.de/actions/gh-release@9560f1070adf2fcd15cfe812a2784d5400847859
        with:
          repo: christofsteel/testrepo
          tag: gh-testrelease
          auth-token: ${{ secrets.GH_TESTREPO_CONTENTS_WRITE }}
          commitish: main
          files: pyproject.toml
