name: draft a release on github (testrepo)

on:
  workflow_dispatch: {}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: https://github.com/softprops/action-gh-release@v3
        with:
          repository: christofsteel/testrepo
          tag_name: gh-testrelease
          token: ${{ secrets.GH_TESTREPO }}
