name: Publish artifacts

on:
  workflow_call:
    inputs:
      version:
        description: 'version tag'
        required: true
        type: string
      release:
        description: 'Type of Build'
        required: true
        type: string
      commit:
        description: 'commit hash'
        required: true
        type: string
      docker:
        description: "Build docker"
        required: true
        type: boolean
      flatpak:
        description: "Build flatpak"
        required: true
        type: boolean
      wine:
        description: "Build wine"
        required: true
        type: boolean
        

jobs:
  publish-docker:
    uses: ./.forgejo/workflows/docker.yaml
    if: ${{ inputs.docker }}
    with:
      version: ${{ inputs.version }}
      commit: ${{ inputs.sha }}
      push: "true"
      release: ${{ inputs.type }}
    secrets: inherit

  publish-flathub:
    uses: ./.forgejo/workflows/external.yaml
    if: ${{ inputs.flatpak }}
    with:
      repo: christofsteel/testrepo
      event: trigger-workflow
      payload: |
        {
          "url":" https://git.k-fortytwo.de/christofsteel/syng-deploytest/actions/runs/${{ forgejo.run_id }}/artifacts/flatpak-yaml-files"
        }
    secrets:
      token: ${{ secrets.GH_TESTREPO }}

  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit }}
      - name: ensure dist
        run: mkdir dist/
      - name: download artifact
        if: ${{ inputs.wine || inputs.flatpak }}
        uses: actions/download-artifact@v3
        with:
          path: dist
      - name: clean and flatten
        if: ${{ inputs.wine || inputs.flatpak }}
        run: |
          rm -rf dist/flatpak-yaml-files || true
          mv dist/**/* dist/
          rmdir dist/* || true
      - uses: actions/forgejo-release@v2.13.4
        with:
          direction: upload
          release-notes-assistant: true
          tag: v${{ inputs.version }}
          sha: ${{ inputs.commit }}
          release-dir: dist
          prerelease: ${{ inputs.release != 'release' }}
          override: true
          verbose: true
