name: Make a new Release

on:
  workflow_dispatch:
    inputs:
      type:
        description: "Type of Release"
        required: true
        type: choice
        options:
          - release
          - prerelease
          - dev
jobs:
  debug:
    uses: ./.forgejo/workflows/debug.yaml
    with:
      release: test123
    # runs-on: ubuntu-latest
    # steps:
    #   - name: print inputs
    #     run: |
    #       echo "type: ${{ inputs.type }}"

  prepare:
    needs: debug
    uses: ./.forgejo/workflows/prepare.yaml
    with:
      release: "release"

  build:
    needs: prepare
    uses: ./.forgejo/workflows/build.yaml
    with:
      type: ${{ inputs.type }}
      version: ${{ needs.prepare.output.version }}
      commit: ${{ needs.prepare.output.commit }}

  publish:
    needs: build
    uses: ./.forgejo/workflows/publish.yaml
    with:
      type: ${{ inputs.type }}
      version: ${{ needs.prepare.output.version }}
      commit: ${{ needs.prepare.output.commit }}
    secrets: inherit


  cleanup:
    needs: [prepare, publish]
    runs-on: ubuntu-latest
    if: ${{ failure() || cancelled() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4        
      - name: Remove Branch
        run: |
          git push origin --delete release-${{needs.prepare.outputs.version}} || true
          git push origin --delete v${{needs.prepare.outputs.version}} || true
