name: Make a new Release

on:
  workflow_dispatch:
    inputs:
      type:
        description: "Type of Release"
        required: true
        type: choice
        options:
          - release
          - prerelease
          - dev


jobs:
  update-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.VERSION }}
      sha: ${{ steps.sha.outputs.SHA }}
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.11.19"      
      - name: check out repo
        uses: actions/checkout@v4
      - name: get current version
        run: |
          REPO_VERSION=$(uv version --short)
          echo "REPO_VERSION=${REPO_VERSION}" >> "$GITHUB_ENV"
      - name: Check for dev version
        run: |
          echo ${{ env.REPO_VERSION }}          
          if [[ "${{ env.REPO_VERSION }}" =~ ^[0-9]*\.[0-9]*\.[0-9]*$ ]]; then echo "This seems like an already released version"; false; else echo "looking good"; true; fi
      - name: set git credentials
        run: |
          git config --global user.name "Forgejo Action CI"
          git config --global user.email "git@git.k-fortytwo.de"
      - name: Bump to stable
        if: ${{ inputs.type == 'release' }}
        run: uv version --bump stable
      - name: get current version
        id: get-version
        run: |
          VERSION=$(uv version --short | sed 's/\.dev/-dev/')
          echo "VERSION=${VERSION}" >> "$GITHUB_OUTPUT"
          echo "VERSION=${VERSION}" >> "$GITHUB_ENV"
      - name: check version against flatpak
        if: ${{ inputs.type == 'release' }}
        run: bash resources/flatpak/check-version.sh ${{ env.VERSION }} 
      - name: Create release-branch
        run: |
          git checkout -b "release-${{env.VERSION}}"
          git add pyproject.toml
          git commit -m "Update to version: ${{env.VERSION}}"
          git push origin "release-${{env.VERSION}}"
      - name: sha
        id: sha
        run: echo "SHA=$(git log -1 --format=%H)" >> $GITHUB_OUTPUT}

  build-wine:
    needs: update-version
    uses: ./.forgejo/workflows/wix.yaml
    with:
      version: ${{ needs.update-version.outputs.version }}
      commit: ${{ needs.update-version.outputs.sha }}

  build-docker:
    needs: update-version
    uses: ./.forgejo/workflows/docker.yaml
    with:
      version: ${{ needs.update-version.outputs.version }}
      commit: ${{ needs.update-version.outputs.sha }}
      push: "false"
      type: ${{ inputs.type }}
    secrets: inherit

  build-flatpak:
    needs: update-version
    uses: ./.forgejo/workflows/flatpak.yaml
    with:
      version: ${{ needs.update-version.outputs.version }}
      commit: ${{ needs.update-version.outputs.sha }}
    secrets:
      GH_TESTREPO: ${{secrets.GH_TESTREPO}}

  build-ok:
    needs: [build-wine, build-flatpak, build-docker, update-version]
    runs-on: ubuntu-latest
    steps:
      - name: Print "Build ok"
        run: echo "Build ok"

  publish-docker:
    needs: [build-ok, update-version]
    uses: ./.forgejo/workflows/docker.yaml
    with:
      version: ${{ needs.update-version.outputs.version }}
      commit: ${{ needs.update-version.outputs.sha }}
      push: "true"
      type: ${{ inputs.type }}
    secrets: inherit

  publish-flathub:
    needs: [build-ok, build-flatpak]
    uses: ./.forgejo/workflows/external.yaml
    with:
      repo: christofsteel/testrepo
      event: trigger-workflow
      payload: |
        {
          "url": "${{ needs.build-flatpak.outputs.artifact_url }}"
        }
    secrets:
      token: ${{ secrets.GH_TESTREPO }}

  publish-release:
    needs: [build-ok, update-version]
    # needs: [build-flatpak, update-version]
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v4
        with:
          ref: ${{needs.update-version.outputs.sha}}
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          path: dist
      - name: clean and flatten
        run: |
          rm -rf dist/flatpak-yaml-files
          mv dist/**/* dist/
          rmdir dist/* || true
      - uses: actions/forgejo-release@v2.13.4
        with:
          direction: upload
          release-notes-assistant: true
          tag: v${{ needs.update-version.outputs.version }}
          sha: ${{ needs.update-version.outputs.sha }}
          release-dir: dist
          prerelease: ${{ inputs.type != 'release' }}

  publish-ok:
    needs: [publish-flathub, publish-docker, publish-release]
    runs-on: ubuntu-latest
    steps:
      - name: Print "Publish ok"
        run: echo "Publish ok"
    

  cleanup:
    needs: [publish-ok, update-version]
    runs-on: ubuntu-latest
    if: ${{ failure() || cancelled() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4        
      - name: Remove Branch
        run: |
          git push origin --delete release-${{needs.update-version.outputs.version}} || true
          git push origin --delete v${{needs.update-version.outputs.version}} || true
