name: Build windows installer and binary

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      version:
        description: 'version tag'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        description: 'version tag'
        required: true
        type: string
      commit:
        description: 'commit hash'
        required: true
        type: string


jobs:
  build-msi:
    runs-on: ubuntu-latest
    container:
      image: tobix/pywine:3.14

    steps:
      - name: set envs
        run: |
          echo "wine=wine" >> ${GITHUB_ENV}
          echo "python=/opt/wineprefix/drive_c/Python/python.exe" >> ${GITHUB_ENV}
          echo "pyinstaller=/opt/wineprefix/drive_c/Python/Scripts/pyinstaller.exe" >> ${GITHUB_ENV}
      - name: print inputs
        run: |
          echo "version: ${{ inputs.version}}"
          echo "commit: ${{ inputs.commit}}"
      - name: install node
        run: apt-get update && apt-get install -y nodejs 7zip jq curl wget
      - name: Checkout code
        uses: actions/checkout@v4        
        with:
          ref: ${{inputs.commit}}

      - name: Get hash and version for cache
        run: |
          echo "syngversion=${{ inputs.version }}" >> $GITHUB_ENV
      - name: Create workdirs
        run: |
          mkdir -p wix
          mkdir -p work/dist
          mkdir -p downloads
          mkdir -p winedl
      - name: Get latest versions for dependencies
        # if: steps.cache-dl.outputs.cache-hit != 'true'
        run: |
          bash latest-win-deps.sh | tee >> ${GITHUB_ENV}
        working-directory: resources/windows
      - name: Cache downloads
        id: cache-dl
        uses: actions/cache@v4
        with:
          path: |
            downloads
          key: downloads-wine${{ env.WINE_VERSION }}-mpv${{ env.MPV_NIGHTLY }}-python${{ env.PYTHON_VERSION }}-mono${{ env.MONO_VERSION }}-deno${{ env.DENO_VERSION }}
      - name: Download everything
        if: steps.cache-dl.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/${{ env.MPV_NIGHTLY }}/ffmpeg-x86_64-git-${{ env.FFMPEG_HASH }}.7z -O ffmpeg.7z
          wget https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/${{ env.MPV_NIGHTLY }}/mpv-dev-x86_64-${{ env.MPV_NIGHTLY }}-git-${{ env.MPV_HASH }}.7z -O mpv.7z
          7z x ffmpeg.7z
          7z x mpv.7z
          rm ffmpeg.7z mpv.7z
          wget https://github.com/wine-mono/wine-mono/releases/download/wine-mono-${{ env.MONO_VERSION }}/wine-mono-${{ env.MONO_VERSION }}-x86.msi -O wine-mono.msi
          wget https://github.com/wixtoolset/wix3/releases/download/wix3141rtm/wix314-binaries.zip
          unzip wix314-binaries.zip -d wix 
          rm wix314-binaries.zip
          wget https://github.com/denoland/deno/releases/download/v${{ env.DENO_VERSION }}/deno-x86_64-pc-windows-msvc.zip
          unzip deno-x86_64-pc-windows-msvc.zip
          rm deno-x86_64-pc-windows-msvc.zip
        working-directory: downloads

      - name: Install wine-mono
        run: |
          xvfb-run -a msiexec /i wine-mono.msi
        working-directory: downloads
      - name: preparing workdir
        run: |
          ls
          cp -r syng work/syng
          cp resources/icons/syng.ico work/
          cp syng/static/background.png work/
          cp syng/static/background20perc.png work/
          cp downloads/libmpv-2.dll work/
          cp downloads/ffmpeg.exe work/
          cp downloads/deno.exe work/
          cp resources/windows/syng.wxs work/
          cp resources/windows/dialog.bmp work/
          cp resources/windows/banner.bmp work/
          cp resources/windows/agpl-3.0.rtf work/
      - name: install syng
        run: |
          echo ${{ env.wine }} ${{ env.python }} -m pip install .[client]
          ${{ env.wine }} ${{ env.python }} -m pip install .[client]
      - name: run PyInstaller (folder)
        run: ${{ env.wine }} ${{ env.pyinstaller }} -n "syng" -w -i'.\syng.ico' --add-data='.\syng.ico;.' --add-data='.\background.png;.' --add-data='.\background20perc.png;.' --add-binary '.\deno.exe;.' --add-binary '.\libmpv-2.dll;.' --add-binary '.\ffmpeg.exe;.' syng/main.py
        working-directory: ./work
      - name: run PyInstaller (standalone)
        run: |
          ${{ env.wine }} ${{ env.pyinstaller }} -n "syng" -F -w -i'.\syng.ico' --add-data='.\syng.ico;.' --add-data='.\background.png;.' --add-data='.\background20perc.png;.' --add-binary '.\deno.exe;.' --add-binary '.\libmpv-2.dll;.' --add-binary '.\ffmpeg.exe;.' syng/main.py
          mv dist/syng.exe dist/syng-${{env.syngversion}}-win64.exe
        working-directory: ./work
      - name: Find wix binaries
        run: |
          HEAT=$(find wix -iname "heat.exe" -exec readlink -f {} \;)
          echo "heat=$HEAT" | tee >> $GITHUB_ENV
          CANDLE=$(find wix -iname "candle.exe" -exec readlink -f {} \;)
          echo "candle=$CANDLE" | tee >> $GITHUB_ENV
          LIGHT=$(find wix -iname "light.exe" -exec readlink -f {} \;)
          echo "light=$LIGHT" | tee >> $GITHUB_ENV
        working-directory: downloads
      - name: run heat
        run: |
          ls -alh ${{env.heat}}
          ls -alh dist/syng/_internal
          ls -alh .
          echo ${{ env.wine }} ${{ env.heat }} dir dist/syng/_internal -var var.Source -dr INSTALLFOLDER -cg InternalGroup -gg -out InternalGroup.wxs
          ${{ env.wine }} ${{ env.heat }} dir dist/syng/_internal -var var.Source -dr INSTALLFOLDER -cg InternalGroup -gg -out InternalGroup.wxs
        working-directory: work
      - name: run candle
        run: |
          cleared_syng_version=$(sed "s/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\).*/\1.\2.\3/" <<< "${{env.syngversion}}")
          echo $cleared_syng_version
          ls
          ${{ env.wine }} ${{ env.candle }} -dSource="dist\\syng\\_internal" InternalGroup.wxs
          ${{ env.wine }} ${{ env.candle }} -dSyngVersion="$cleared_syng_version" syng.wxs
        working-directory: work
      - name: run light
        run: |
          ${{ env.wine }} ${{ env.light }} -ext WixUIExtension -sval -out syng-installer-${{ env.syngversion }}-win64.msi InternalGroup.wixobj syng.wixobj
          ls -alh dist/
        working-directory: work
      - name: create portable app artifact
        uses: actions/upload-artifact@v3
        with:
          name: syng-${{ env.syngversion }}-win64-exe
          path: ./work/dist/syng-${{env.syngversion}}-win64.exe
      - name: create installer artifact
        uses: actions/upload-artifact@v3
        with:
          name: syng-installer-${{ env.syngversion }}-win64-msi
          path: ./work/syng-installer-${{ env.syngversion }}-win64.msi
